### ISSUE TITLE
badge gets bigger each time an app is launched

### ISSUE THREAD

**Issue by dhuyvett** [Cobinja/CobiWindowList#30] opened 2020-02-11 23:13 UTC
With the latest build, each time I launch a pinned app by clicking on it, the black circle behind the number is a little bigger, until the black circle completely covers the app icon.

Restarting cinnamon resets the badge size.

**Comment by Cobinja** [comment] 2020-02-19 14:19
Which cinnamon theme do you use? And can you provide some screenshots?

**Comment by dhuyvett** [comment] 2020-02-19 15:54
my current desktop theme is Adapta-Nokto  But I see this with every theme I've tried.

In the screenshot, all icons are pinned.  I opened firefox once, closed and re-opened chrome 3 times, and closed and re-opened chromium 5 times

![Screenshot from 2020-02-19 07-48-41](https://user-images.githubusercontent.com/5666117/74848656-bf17f800-52ec-11ea-9f68-3d456910fa57.png)

**Comment by Cobinja** [comment] 2020-02-19 17:54
Does this only happen when closing and reopening them or also when you just add windows (like opening nemo 3 times, does the size increase with every opened new window)?
Which distro do you use? Which cinnamon version?

**Comment by dhuyvett** [comment] 2020-02-19 21:51
the size only increases when I close all instances of the app and then re-open it.  If at least 1 instance of the app is left running, I can start and stop additional instances without having the badge grow.

This is Mint 19.3 , Cinnamon 4.4.8

**Comment by Cobinja** [comment] 2020-02-20 14:09
I can't reproduce it here, so fixing it is a bit of a problem.
Can you test the following:

in $HOME/.local/share/cinnamon/applets/windowlist@cobinja.de/4.0
you find a file called applet.js.
Please change line 1043 to
`let [width, height] = this._labelNumber.get_size();`
and move line 1047 above it.
Tell me if that helps (you'll have to restart cinnamon for it to take effect).

**Comment by dhuyvett** [comment] 2020-02-20 18:55
that fixes it

**Closed as completed** 2020-02-21 04:53 UTC
